# Generated by Django 3.0.6 on 2020-05-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=50, verbose_name='職業')),
                ('income', models.IntegerField(verbose_name='年収')),
                ('weekly_holiday', models.CharField(max_length=50, verbose_name='週休')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='苗字')),
                ('last_name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('location', models.CharField(max_length=50, verbose_name='所在地')),
                ('Profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstappps.Profession')),
            ],
        ),
    ]
