# Generated by Django 3.0.6 on 2020-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstappps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='savings',
        ),
        migrations.AddField(
            model_name='profession',
            name='weekly_holiday',
            field=models.CharField(default='週休2日', max_length=50, verbose_name='週休'),
            preserve_default=False,
        ),
    ]
